name: 'DGP Conformance Verification'
description: 'Verify DGP v1.0 conformance by running canonical vector tests'
author: 'dgp-standard'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  language:
    description: 'Implementation language (python or node)'
    required: true
  test_command:
    description: 'Command to run conformance tests'
    required: false
    default: 'auto'
  working_directory:
    description: 'Working directory for running tests'
    required: false
    default: '.'

outputs:
  conformant:
    description: 'Whether the implementation passed 8/8 canonical vectors'
    value: ${{ steps.verify.outputs.conformant }}
  vectors_passed:
    description: 'Number of canonical vectors passed'
    value: ${{ steps.verify.outputs.vectors_passed }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      if: inputs.language == 'python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Setup Node.js
      if: inputs.language == 'node'
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Python dependencies
      if: inputs.language == 'python'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        pip install pytest
    
    - name: Install Node dependencies
      if: inputs.language == 'node'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if [ -f package.json ]; then
          npm install
        fi
    
    - name: Verify DGP Conformance
      id: verify
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        LANGUAGE: ${{ inputs.language }}
        TEST_COMMAND: ${{ inputs.test_command }}
        DGP_RESULT_PATH: .dgp/conformance-result.json
        DGP_EXPECTED_CANONICAL_HASH: b551d99d6c6ac9dfebd660ad1be2e326ce31aef372a659fa7a6a5af1bf33b9c2
        DGP_CANONICAL_URL: https://raw.githubusercontent.com/dgp-standard/dgp-standard-dgp-spec/v1.0.1/conformance/canonical-v1.json
      run: |
        # Determine test command
        if [ "$TEST_COMMAND" = "auto" ]; then
          if [ "$LANGUAGE" = "python" ]; then
            CMD="pytest tests/test_contract_compliance.py -v"
          elif [ "$LANGUAGE" = "node" ]; then
            CMD="npm test"
          fi
        else
          CMD="$TEST_COMMAND"
        fi
        
        echo "Running: $CMD"

        # Validate sealed canonical vectors identity from pinned source
        canonical_sha=$(curl -fsSL "$DGP_CANONICAL_URL" | jq -r '.sha256')
        if [ -z "$canonical_sha" ] || [ "$canonical_sha" = "null" ]; then
          echo "❌ canonical-v1.json is missing sha256"
          echo "conformant=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        if echo "$canonical_sha" | grep -qiE 'compute|placeholder'; then
          echo "❌ canonical-v1.json sha256 is unsealed placeholder: $canonical_sha"
          echo "conformant=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        if [ "$canonical_sha" != "$DGP_EXPECTED_CANONICAL_HASH" ]; then
          echo "❌ canonical-v1.json sha256 mismatch"
          echo "Expected: $DGP_EXPECTED_CANONICAL_HASH"
          echo "Got:      $canonical_sha"
          echo "conformant=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        # Run tests normally (exit code matters)
        $CMD

        # Require machine-readable result artifact
        if [ ! -f "$DGP_RESULT_PATH" ]; then
          echo "❌ Missing conformance result file: $DGP_RESULT_PATH"
          echo "Implementations MUST write JSON results to this path."
          echo "conformant=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        # Validate JSON contract
        if ! jq -e 'type == "object"' "$DGP_RESULT_PATH" > /dev/null; then
          echo "❌ Invalid conformance result JSON: root must be an object"
          cat "$DGP_RESULT_PATH"
          echo "conformant=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        if ! jq -e '
          (.dgp_version | type == "string") and
          (.engine | type == "string") and
          (.vectors_passed | type == "number") and
          (.vectors_total | type == "number") and
          (.canonical_hash | type == "string") and
          (.timestamp | type == "string")
        ' "$DGP_RESULT_PATH" > /dev/null; then
          echo "❌ Invalid conformance result JSON: required typed fields are missing"
          cat "$DGP_RESULT_PATH"
          echo "conformant=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        passed=$(jq -r '.vectors_passed' "$DGP_RESULT_PATH")
        total=$(jq -r '.vectors_total' "$DGP_RESULT_PATH")
        hash=$(jq -r '.canonical_hash' "$DGP_RESULT_PATH")

        if [ "$hash" != "$DGP_EXPECTED_CANONICAL_HASH" ]; then
          echo "❌ Canonical hash mismatch"
          echo "Expected: $DGP_EXPECTED_CANONICAL_HASH"
          echo "Got:      $hash"
          cat "$DGP_RESULT_PATH"
          echo "conformant=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        if [ "$passed" != "$total" ]; then
          echo "❌ Not all vectors passed: $passed/$total"
          cat "$DGP_RESULT_PATH"
          echo "conformant=false" >> $GITHUB_OUTPUT
          echo "vectors_passed=$passed" >> $GITHUB_OUTPUT
          exit 1
        fi

        echo "✅ DGP v1.0 Conformant ($passed/$total) with pinned canonical hash"
        echo "conformant=true" >> $GITHUB_OUTPUT
        echo "vectors_passed=$passed" >> $GITHUB_OUTPUT
